[workspace]
resolver = "2"
members = ["gbemu_rust_app", "gbemu_rust_lib"]

[workspace.dependencies]
tracing = "0.1.41"
tracing-appender = "0.2.3"
tracing-core = "0.1.33"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
