[package]
name = "gbemu_rust"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 0

[profile.test]
opt-level = 3

[profile.bench]
opt-level = 3

[profile.release]
opt-level = 3

[dependencies]
lazy_static = "1.5.0"
