[package]
name = "gbemu_rust"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 0

[profile.test]
opt-level = 3

[profile.bench]
opt-level = 3

[profile.release]
opt-level = 3

[dependencies]
log = "0.4.27"
tracing = "0.1.41"
tracing-appender = "0.2.3"
tracing-subscriber = "0.3.19"
