[package]
name = "gbemu_rust_lib"
version = "0.1.0"
edition = "2024"

[[bench]]
name = "bench_step"
harness = false

[dependencies]
criterion.workspace = true
regex.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-core.workspace = true
tracing-subscriber.workspace = true
serde.workspace = true
