name: Build and test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - '*'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --profile release

  build-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: latest
      - name: Build docs
        run: mdbook build docs

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: ./docs/book/

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: taiki-e/install-action@nextest
      - name: Run tests and generate coverage
        uses: actions-rs/cargo@v1
        with:
          command: llvm-cov
          args: nextest --html

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: ./target/llvm-cov/html/
